# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-31 15:40
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('ifsc', models.CharField(max_length=128)),
                ('branch', models.CharField(max_length=128)),
                ('account_type', models.CharField(choices=[(b'savings', b'Savings'), (b'current', b'Current')], max_length=128)),
                ('account_no', models.CharField(max_length=128)),
                ('first_time_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cheque_return_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'bank_account',
                'verbose_name': 'bank account',
                'verbose_name_plural': 'bank accounts',
            },
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('first_time_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'cash_account',
                'verbose_name': 'cash account',
                'verbose_name_plural': 'cash accounts',
            },
        ),
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.PositiveIntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('a_id',),
                'db_table': 'finance_cash_transfer',
                'verbose_name': 'cash transafer',
                'verbose_name_plural': 'cash transafers',
            },
        ),
        migrations.CreateModel(
            name='Journel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bank_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bank_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'finance_journel',
                'verbose_name': 'journel',
                'verbose_name_plural': 'journels',
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.PositiveIntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('a_id',),
                'db_table': 'staff_salary_payment',
                'verbose_name': 'staff salary payment',
                'verbose_name_plural': 'staff salary payments',
            },
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tax_category',
                'verbose_name': 'tax category',
                'verbose_name_plural': 'tax categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.PositiveIntegerField(db_index=True)),
                ('transaction_type', models.CharField(blank=True, choices=[(b'income', b'Income'), (b'expense', b'Expense')], default=b'income', max_length=7)),
                ('transaction_mode', models.CharField(choices=[(b'cash', b'Cash'), (b'bank', b'Bank')], default=b'cash', max_length=15)),
                ('payment_mode', models.CharField(blank=True, choices=[(b'cheque_payment', b'Cheque Payment'), (b'internet_banking', b'Internet Banking'), (b'card_payment', b'Card Payment')], max_length=128, null=True)),
                ('cheque_details', models.CharField(blank=True, max_length=128, null=True)),
                ('is_cheque_withdrawed', models.BooleanField(default=False)),
                ('is_cheque_returned', models.BooleanField(default=False)),
                ('card_details', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_to', models.CharField(blank=True, choices=[(b'cash_account', b'Cash Account'), (b'bank_account', b'Bank Account')], default=b'cash_account', max_length=128, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('first_transaction', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date',),
                'db_table': 'transaction',
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=128)),
                ('category_type', models.CharField(choices=[(b'income', b'Income'), (b'expense', b'Expense')], max_length=7)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_transactioncategory_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('category_type',),
                'db_table': 'transaction_category',
                'verbose_name': 'transaction category',
                'verbose_name_plural': 'transaction categories',
            },
        ),
    ]
