# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-31 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_auto_20190831_2110'),
        ('distributors', '0002_auto_20190831_2110'),
        ('main', '0001_initial'),
        ('vendors', '0001_initial'),
        ('staffs', '0001_initial'),
        ('sales', '0001_initial'),
        ('finance', '0003_auto_20190831_2110'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.Staff'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='staff_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.StaffSalary'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.TransactionCategory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_transaction_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vender_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_paymenttransaction_objects', to='purchases.CollectAmounts'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_taxcategory_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop'),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='updator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_taxcategory_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffsalarypayment',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_staffsalarypayment_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffsalarypayment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop'),
        ),
        migrations.AddField(
            model_name='staffsalarypayment',
            name='staff_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staffs.StaffSalary'),
        ),
        migrations.AddField(
            model_name='staffsalarypayment',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Transaction'),
        ),
        migrations.AddField(
            model_name='staffsalarypayment',
            name='updator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_staffsalarypayment_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journel',
            name='asset_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.AssetPurchase'),
        ),
        migrations.AddField(
            model_name='journel',
            name='collect_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_amountjournel_objects', to='sales.CollectAmount'),
        ),
        migrations.AddField(
            model_name='journel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
        migrations.AddField(
            model_name='journel',
            name='customer_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_paymentjournel_objects', to='sales.CustomerPayment'),
        ),
        migrations.AddField(
            model_name='journel',
            name='paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.PaidAmount'),
        ),
        migrations.AddField(
            model_name='journel',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.Purchase'),
        ),
        migrations.AddField(
            model_name='journel',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returnjournel_objects', to='sales.ProductReturn'),
        ),
        migrations.AddField(
            model_name='journel',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salejournel_objects', to='sales.Sale'),
        ),
        migrations.AddField(
            model_name='journel',
            name='sale_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_returnjournel_objects', to='sales.SaleReturn'),
        ),
        migrations.AddField(
            model_name='journel',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop'),
        ),
        migrations.AddField(
            model_name='journel',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Transaction'),
        ),
        migrations.AddField(
            model_name='journel',
            name='vender_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_paymentjournel_objects', to='purchases.CollectAmounts'),
        ),
        migrations.AddField(
            model_name='journel',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor'),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_cashtransfer_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributors.Distributor'),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='from_cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_cashtransfer_objects', to='finance.CashAccount'),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop'),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='to_cash_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_cashtransfer_objects', to='finance.CashAccount'),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='updator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_cashtransfer_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_cashaccount_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop'),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='updator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_cashaccount_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_bankaccount_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_bankaccount_objects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='transactioncategory',
            unique_together=set([('category_type', 'name', 'shop')]),
        ),
    ]
