# Generated by Django 3.1.5 on 2021-01-24 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_auto_20190831_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directstocktransfer',
            name='distributor',
            field=models.ForeignKey(limit_choices_to={'is_salesman': False}, on_delete=django.db.models.deletion.CASCADE, to='distributors.distributor'),
        ),
        migrations.AlterField(
            model_name='distributorstocktransfer',
            name='from_distributor',
            field=models.ForeignKey(limit_choices_to={'is_salesman': False}, on_delete=django.db.models.deletion.CASCADE, related_name='from_distributorstocktransfer_objects', to='distributors.distributor'),
        ),
        migrations.AlterField(
            model_name='distributorstocktransfer',
            name='to_distributor',
            field=models.ForeignKey(limit_choices_to={'is_salesman': False}, on_delete=django.db.models.deletion.CASCADE, related_name='to_distributorstocktransfer_objects', to='distributors.distributor'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='distributor',
            field=models.ForeignKey(limit_choices_to={'is_salesman': False}, on_delete=django.db.models.deletion.CASCADE, to='distributors.distributor'),
        ),
    ]
