# Generated by Django 3.1.5 on 2021-01-24 07:34

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='application',
            field=models.FileField(upload_to='app/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='bill_print_type',
            field=models.CharField(choices=[('a4', 'A4'), ('compact', 'Compact(77mm)')], default='a4', max_length=128),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='shop/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli ', 'Dadra and Nagar Haveli '), ('Daman and Diu', 'Daman and Diu'), ('National Capital Territory of Delhi', 'National Capital Territory of Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Lakshadweep union territory', 'Lakshadweep union territory'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry union territory', 'Puducherry union territory'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='Kerala', max_length=128),
        ),
        migrations.AlterField(
            model_name='shop',
            name='theme',
            field=models.CharField(choices=[('teal', 'Teal'), ('blue', 'Blue'), ('bluegrey', 'Blue Grey'), ('cyan-600', 'Cyan'), ('green', 'Green'), ('lightgreen', 'Light Green'), ('purple-400', 'Purple'), ('red-400', 'Red'), ('pink-400', 'Pink'), ('brown', 'Brown'), ('grey-600', 'Grey'), ('orange', 'Orange')], default='teal', max_length=40),
        ),
    ]
