# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-08-31 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anniversary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop')),
            ],
            options={
                'db_table': 'task_anniversary',
                'verbose_name': 'anniversary',
                'verbose_name_plural': 'anniversaries',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('holiday', 'Holiday'), ('leave', 'Leave'), ('task', 'Task')], max_length=128)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=128)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('anniversary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Anniversary')),
            ],
            options={
                'db_table': 'event',
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.PositiveIntegerField(db_index=True)),
                ('holiday_category', models.CharField(choices=[('public', 'Public'), ('national', 'National')], default='public', max_length=10)),
                ('date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_holiday_objects', to=settings.AUTH_USER_MODEL)),
                ('updator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_holiday_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'holiday',
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holidays',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to=b'')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('remind_on', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_reminder_objects', to=settings.AUTH_USER_MODEL)),
                ('updator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_reminder_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_reminder',
                'verbose_name': 'reminder',
                'verbose_name_plural': 'reminders',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('a_id', models.PositiveIntegerField(db_index=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('from_time', models.DateTimeField(blank=True, null=True)),
                ('to_time', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_task_objects', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.Staff')),
                ('updator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='updator_task_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks_task',
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Holiday'),
        ),
        migrations.AddField(
            model_name='event',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shop'),
        ),
        migrations.AddField(
            model_name='event',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
