# Generated by Django 3.1.5 on 2021-01-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
