# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-07 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
