# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-04 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190831_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='unit_type',
            field=models.CharField(choices=[('quantity', 'Quantity')], default='quantity', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('quantity', 'Quantity')], default='quantity', max_length=128),
        ),
    ]
