# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-09-06 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190906_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='best_before',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='product',
            name='net_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packing_charge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_expiry_before',
        ),
    ]
